#!/usr/bin/env python3
"""Generate `src/regex/props_emoji.rs` — the ECMAScript *properties of strings*
(`\\p{RGI_Emoji}` and friends, valid only in a `v`-mode class).

Usage:

    tools/gen_unicode_emoji.py <ucd-dir> > src/regex/props_emoji.rs

`<ucd-dir>` must contain `emoji-sequences.txt` and `emoji-zwj-sequences.txt`,
downloaded from https://www.unicode.org/Public/<version>/emoji/ .

Each file lists `CP [CP …] ; Type_Field ; name` per line, where the code points
may be a `AAAA..BBBB` range (single-code-point entries only). We group by type
field and emit one `&str` per property in which the sequences are separated by
`\\n` (which no emoji sequence contains), so the tables cost only their bytes in
the binary rather than a slice-of-slices' worth of pointers.
"""

import sys
import os

EMOJI_VERSION = "17.0"

# Type field -> emitted static name. `RGI_Emoji` is the union of all of these
# (ED-27 in UTS #51) and is assembled at runtime, not stored twice.
TYPES = [
    ("Basic_Emoji", "BASIC_EMOJI"),
    ("Emoji_Keycap_Sequence", "EMOJI_KEYCAP_SEQUENCE"),
    ("RGI_Emoji_Flag_Sequence", "RGI_EMOJI_FLAG_SEQUENCE"),
    ("RGI_Emoji_Modifier_Sequence", "RGI_EMOJI_MODIFIER_SEQUENCE"),
    ("RGI_Emoji_Tag_Sequence", "RGI_EMOJI_TAG_SEQUENCE"),
    ("RGI_Emoji_ZWJ_Sequence", "RGI_EMOJI_ZWJ_SEQUENCE"),
]

FILES = ["emoji-sequences.txt", "emoji-zwj-sequences.txt"]


def parse(paths):
    """-> {type field: [sequence as tuple of code points]}, in file order."""
    out = {}
    for path in paths:
        with open(path, encoding="utf-8") as fh:
            for line in fh:
                line = line.split("#", 1)[0]
                parts = [f.strip() for f in line.split(";")]
                if len(parts) < 2 or not parts[0]:
                    continue
                cps, ty = parts[0], parts[1]
                bucket = out.setdefault(ty, [])
                if ".." in cps:
                    lo, hi = (int(x, 16) for x in cps.split(".."))
                    bucket.extend((cp,) for cp in range(lo, hi + 1))
                else:
                    bucket.append(tuple(int(x, 16) for x in cps.split()))
    return out


def rust_str(seqs):
    """Sequences -> a Rust string literal, `\\n`-separated, `\\u{…}`-escaped."""
    return "\\n".join("".join(f"\\u{{{cp:X}}}" for cp in seq) for seq in seqs)


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    data = parse([os.path.join(sys.argv[1], f) for f in FILES])
    major, minor = EMOJI_VERSION.split(".")

    out = sys.stdout.write
    out(
        f"""//! Emoji *properties of strings* for regex `\\p{{…}}` escapes in `v` mode.
//!
//! @generated by `tools/gen_unicode_emoji.py` from the Unicode Emoji v{EMOJI_VERSION}
//! data files (`emoji-sequences.txt`, `emoji-zwj-sequences.txt`) — DO NOT EDIT.
//! Regenerate with:
//!
//! ```text
//! tools/gen_unicode_emoji.py <ucd-dir> > src/regex/props_emoji.rs
//! ```
//!
//! Each static holds that property's sequences separated by `\\n` — a code point
//! no emoji sequence contains — so the data costs its bytes and nothing more.
//! [`sequences`] splits one back into the code-point vectors the `v`-mode class
//! compiler wants. `RGI_Emoji` is ED-27's union of all six and is assembled on
//! demand rather than stored a second time.

use alloc::vec::Vec;

/// The Unicode Emoji version these tables were generated from.
#[cfg_attr(not(test), allow(dead_code))]
pub(crate) const EMOJI_VERSION: (u8, u8) = ({major}, {minor});
"""
    )

    for ty, const in TYPES:
        seqs = data.get(ty)
        if not seqs:
            sys.exit(f"error: no entries for {ty}")
        out(f'\n/// `\\p{{{ty}}}` — {len(seqs)} sequences.\n')
        out(f'static {const}: &str = "{rust_str(seqs)}";\n')

    names = ",\n        ".join(f'"{ty}" => {const}' for ty, const in TYPES)
    union = ", ".join(const for _, const in TYPES)
    out(
        f"""
/// The sequences of the property of strings `name`, or `None` if `name` is not
/// one. `RGI_Emoji` is the union of the other six, in their data-file order.
pub(crate) fn sequences(name: &str) -> Option<Vec<Vec<u32>>> {{
    if name == "RGI_Emoji" {{
        return Some(
            [{union}]
                .iter()
                .flat_map(|table| split(table))
                .collect(),
        );
    }}
    let table = match name {{
        {names},
        _ => return None,
    }};
    Some(split(table))
}}

/// Splits a `\\n`-separated table into its sequences.
fn split(table: &str) -> Vec<Vec<u32>> {{
    table
        .split('\\n')
        .map(|seq| seq.chars().map(u32::from).collect())
        .collect()
}}
"""
    )


if __name__ == "__main__":
    main()
