#!/usr/bin/env python3
"""Generate `src/nbexec/intl_aliases.rs` — the CLDR alias tables that
`Intl.getCanonicalLocales` applies to BCP-47 *extension* subtags.

Usage:

    tools/gen_cldr_bcp47_aliases.py <cldr-dir> > src/nbexec/intl_aliases.rs

`<cldr-dir>` must contain these files from https://github.com/unicode-org/cldr :

    common/bcp47/timezone.xml            -> `-u-tz-` deprecated time zones
    common/bcp47/transform.xml           -> `-t-` tvalue aliases (e.g. m0-names)
    common/supplemental/supplementalMetadata.xml -> `-u-rg-`/`-u-sd-` subdivisions

Only the *deprecated -> preferred* direction is emitted; each table is a sorted
`&[(&str, &str)]` searched by binary search. The `intl` crate canonicalizes the
base subtags (language/script/region/variant); these are the extension-subtag
aliases it does not carry.
"""

import re
import sys
import os

TZ = re.compile(r'<type name="([^"]+)"[^>]*deprecated="true"[^>]*preferred="([^"]+)"')
# `alias` may list several space-separated deprecated spellings for one type.
TRANSFORM = re.compile(r'<type name="([^"]+)"[^>]*alias="([^"]+)"')
SUBDIV = re.compile(r'<subdivisionAlias type="([^"]+)" replacement="([^"]+)"')


def read(path):
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def emit(out, name, doc, pairs):
    pairs = sorted(set(pairs))
    out(f"\n/// {doc} — {len(pairs)} aliases.\n")
    out(f'pub(crate) static {name}: &[(&str, &str)] = &[\n')
    for a, b in pairs:
        out(f'    ("{a}", "{b}"),\n')
    out("];\n")


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    root = sys.argv[1]

    def find(*rel):
        for r in rel:
            p = os.path.join(root, r)
            if os.path.exists(p):
                return p
        sys.exit(f"error: none of {rel} found under {root}")

    tz_src = read(find("timezone.xml", "common/bcp47/timezone.xml"))
    tr_src = read(find("transform.xml", "common/bcp47/transform.xml"))
    sd_src = read(
        find("suppmeta.xml", "supplementalMetadata.xml",
             "common/supplemental/supplementalMetadata.xml")
    )

    tz = [(dep, pref) for dep, pref in TZ.findall(tz_src)]
    # A `-t-` tvalue alias maps each spelling in `alias` to the canonical `name`.
    # CLDR writes multi-subtag spellings with `-`; those cannot appear as a single
    # BCP-47 subtag, so only single-subtag aliases are usable here.
    tr = [
        (dep, name)
        for name, alias in TRANSFORM.findall(tr_src)
        for dep in alias.split()
        if "-" not in dep
    ]
    # Subdivision replacements may list several candidates; the first is preferred.
    # A replacement that is a plain region code (`AX`) is not a subdivision alias.
    sd = [
        (dep, rep.split()[0].lower())
        for dep, rep in SUBDIV.findall(sd_src)
        if len(rep.split()[0]) > 3
    ]

    out = sys.stdout.write
    out(
        """//! CLDR alias tables for BCP-47 *extension* subtags.
//!
//! @generated by `tools/gen_cldr_bcp47_aliases.py` from CLDR
//! (`common/bcp47/timezone.xml`, `common/bcp47/transform.xml`,
//! `common/supplemental/supplementalMetadata.xml`) — DO NOT EDIT.
//!
//! `Intl.getCanonicalLocales` replaces deprecated subtags with their preferred
//! forms. The `intl` crate's alias corpus covers the *base* subtags (language,
//! script, region, variant); these are the extension-subtag aliases it does not
//! carry — `-u-tz-`, `-u-rg-`/`-u-sd-`, and `-t-` tvalues. Each table is sorted,
//! so [`lookup`] binary-searches it.

/// The preferred replacement for deprecated subtag `key` in `table`, if any.
pub(crate) fn lookup(table: &[(&'static str, &'static str)], key: &str) -> Option<&'static str> {
    table
        .binary_search_by(|(k, _)| (*k).cmp(key))
        .ok()
        .map(|i| table[i].1)
}
"""
    )
    emit(out, "TIMEZONE", "`-u-tz-` deprecated time-zone ids", tz)
    emit(out, "TRANSFORM_VALUE", "`-t-` deprecated tvalue subtags", tr)
    emit(out, "SUBDIVISION", "`-u-rg-`/`-u-sd-` deprecated subdivision ids", sd)


if __name__ == "__main__":
    main()
